### ISSUE TITLE
[MOD] Every Someguy2000 quests / companions mods

### ISSUE THREAD

**Issue by TheFrenchGhosty** [VivaNewVegas/vivanewvegas.github.io#25]
## What is the name of mod?

New Vegas Bounties 1 - 2 - 3
Russell
...

## What kind of mod is it?

Quests and Companions 

## The link of the mod

https://www.nexusmods.com/newvegas/users/2159825?tab=user+files

## Any additional context

Someguy2000's mods are the most endorsed quests/companions mods. In my opinion they should be part of Viva New Vegas.

I'm really curious as to why they aren't already included

**Comment by TDarkShadow** [comment]
They aren't included because there is already a lot of extra quests going with all the content, and there has to be a limited amount of quests or you have to deal with save bloat.
That being said, you can add them yourself if you want to, but you have to exchange some of the other quests mods in turn.

**Comment by TheFrenchGhosty** [comment]
>They aren't included because there is already a lot of extra quests going with all the content, and there has to be a limited amount of quests or you have to deal with save bloat.

Is New Vegas that fragile to suffer from save bloat with less than 20 quests mods? Is it really necessary to remove some to add others?

When I modded Skyrim I don't remember it to be a problem, is the engine that different between both game?

**Comment by VivaNewVegas** [comment]
Yeah, the creation engine is much newer, and its 64bit vs. New Vegas which is 32bit. Obsidian also royally fucked the engine a bit so its even more of a problem then it is with their other gamebryo games. With quest mods, every NPC you talk to, interior you enter, items you pick up, objects you move, etc. are stored on your save and can make it too big very quickly. You can try to add those mods on top of the ones in the guide, but towards the end of your playthrough you might start to encounter large stutters, odd bugs, and potential crashes as your save gets bigger and bigger. And just to add if you're curious, Someguy's mods aren't in the guide in the first place because I don't like them that much. They have major balance issues, some low quality/non-existent voice acting especially in the earlier series, and this one is always hard to explain but I feel like they overstep their bounds as quest mods. They add these massive new factions like the Syndicate, who are apparently a massive problem in the Mojave but are never seen or mentioned outside a quest in the Inheritence. That being said, they are made well enough for quest mods and I understand the appeal. They should be physically compatible out of the box with the guide, the worst you might see is buildings/terrain from other mods overlapping with it.

**Comment by TheFrenchGhosty** [comment]
>Yeah, the creation engine is much newer, and its 64bit vs. New Vegas which is 32bit. Obsidian also royally fucked the engine a bit so its even more of a problem then it is with their other gamebryo games.

I was talking about Oldrim, but good to know it's even worse on NV.

>With quest mods, every NPC you talk to, interior you enter, items you pick up, objects you move, etc. are stored on your save and can make it too big very quickly. You can try to add those mods on top of the ones in the guide, but towards the end of your playthrough you might start to encounter large stutters, odd bugs, and potential crashes as your save gets bigger and bigger.

Is it an issue only on NV or was it also an issue in Oldrim?

In my experience modding oldrim around 2 years ago, I could throw anything at it be it visual mod / content mod without any issue (I didn't even made custom patch back then and didn't noticed any problem).


>And just to add if you're curious, Someguy's mods aren't in the guide in the first place because I don't like them that much. They have major balance issues, some low quality/non-existent voice acting especially in the earlier series, and this one is always hard to explain but I feel like they overstep their bounds as quest mods. They add these massive new factions like the Syndicate, who are apparently a massive problem in the Mojave but are never seen or mentioned outside a quest in the Inheritence.

That's good to know, I never tried then (I never completed New Vegas itself in the first place), I guess I should focus on the currently included content I guess then. I really thought it was "the best of the best" considering the fact that it's always recommended / have lots of endorsement (not that they actually mean something).

**Comment by VivaNewVegas** [comment]
I have 0 experience with Skyrim, so I can't say. And Someguy's mods are definitely good on their own and their incredibly impressive for one person to have made, but I just don't think they fit very well in a normal playthrough since you notice how disconnected the stroy feels from the vanilla story and become pretty OP by the ends of them.

**Comment by TheFrenchGhosty** [comment]
>And Someguy's mods are definitely good on their own and their incredibly impressive for one person to have made, but I just don't think they fit very well in a normal playthrough since you notice how disconnected the stroy feels from the vanilla story and become pretty OP by the ends of them.

Thanks, I will stick to Viva New Vegas then, thanks again for your work!
